### ISSUE TITLE
Multiple 'Not found' elements when a single one is enough

### ISSUE THREAD

**Issue by eddiesholl** [likun7981/auto-breadcrumb#2]
If the number of unmatched routes is greater than 1, it's probably still only worth showing a single `notFound` element. It seems overkill, and kind of unexpected, to ever display more than 1.

If I have static routes configured with
```
staticRoutesMap: {
  '/': 'My App',
  '/about': 'About'
},
notFound: 'Not Found'
```

if I visit `/foo/bar` the breadcrumbs will display `My App > Not Found > Not Found`, with the first `Not Found` being clickable. I would say there should only ever be a single `Not Found`, and it's not clickable.

**Comment by likun7981** [comment]
Hi @eddiesholl ,

Your advice is good !    I will fix it in the next version.
