### ISSUE TITLE
Using auto-breadcrumb with antd via Breadcrumb and BreadcrumbItem config

### ISSUE THREAD

**Issue by clodal** [likun7981/auto-breadcrumb#3]
I'm trying to use auto-breadcrumb with antd like in [demo](https://likun7981.github.io/auto-breadcrumb/#/3/2/0/2/0) but i'm having problems setting the config. I understand the config for the breadcrumb ui components are described in the readme as copied below:

keyName | type | default | description
-- | -- | -- | --
Breadcrumb | ReactComponent | ul | The Breadcrumb container
BreadcrumbItem | ReactComponent | li | The Breadcrumb Item

However, when i tried setting the config like so, it doesn't work:

```
import AutoBreadcrumbs from 'auto-breadcrumb';
import Breadcrumb from 'antd/lib/breadcrumb';
config = {
  Breadcrumb: <Breadcrumb />,
  BreadcrumbItem: <Breadcrumb.Item />,
  ..
}
const Breadcrumbs = AutoBreadcrumbs(config);
```

Then, I noticed in the [source code](https://github.com/likun7981/auto-breadcrumb/blob/master/src/index.js#L20), that ul and li are set like strings, so i also tried this, which also failed:
```
import AutoBreadcrumbs from 'auto-breadcrumb';
import Breadcrumb from 'antd/lib/breadcrumb';
config = {
  Breadcrumb: 'Breadcrumb',
  BreadcrumbItem: 'Breadcrumb.Item',
  ..
}
const Breadcrumbs = AutoBreadcrumbs(config);
```

Would you please share how you did it? Thanks!

**Comment by clodal** [comment]
Woops, got it. Sorry, my bad.

```
config = {
  Breadcrumb: Breadcrumb,
  BreadcrumbItem: Breadcrumb.Item,
}
```

**Comment by likun7981** [comment]
Hi @clodal , thank you for using `auto-breadcrumb`,

It is my fault, I do not update the `master branch demo code` ,  but you can see it on [gh-pages branch](https://github.com/likun7981/auto-breadcrumb/blob/gh-pages/demo/RecursivePaths.js#L15-L16)

If you think it's easy to use, please give me a star,  😄
