### ISSUE TITLE
Proposal: customRoutesMap

### ISSUE THREAD

**Issue by clodal** [likun7981/auto-breadcrumb#4]
Hi there, thanks for this. Would you help me consider this use case for singular and plural routes? Looking forward to your feedback.

### Current Outcome
Say we have the following urls:
- Product Listing Page:  `/products`
- Product Detail Page: `/product/:slug`

and autobreadcrumb config as such:
```javascript
dynamicRoutesMap: {
  '/product/:slug': ({ slug }) => `${slug}`,
},
```

Now, In Product Detail Page, breadcrumbs are showing:
`Home > Product > My-First-Product`

### Problem
However, **`Product`** in the breadcrumb above example above is linking to `/product`. There is no such url.

### Desired outcome
BreadcrumbItem for **Product** should link to `/products` instead of `/product`. 

### Proposal
Add a `customRouteMap` config that will allow complete override of the displayed breadcrumb for that url. 

Example:
```javascript
dynamicRoutesMap: { .. },
customRoutesMap: {
  '/product/:slug': [<Link to="/products">Products</Link>, ({ slug }) => `${slug}`],
},
```
Corresponding breadcrumbs:
`Home > Products > My-First-Product`
with **Products** linking to `/products/`

**Comment by likun7981** [comment]
Thank you for your proposal.

 I think the `Detail Page Url` should be `/products/:slug` instead of `/product/:slug`  in terms of `Restful Standard`, you can see  [restful-url](https://github.com/WhiteHouse/api-standards#restful-urls). 

But  the custom item is also needed, I think the better solution way is to provide a `itemRender` configuration option, and then it  give some callback params, the developer could render item according to these params, at the same time, I can remove `LinkComponent` this configuration option, because everything you can custom for item. 

You can see the design from [ant-design breadcrumb](https://github.com/ant-design/ant-design/blob/master/components/breadcrumb/Breadcrumb.tsx#L30-L36),  for router2 and router3

What do you think about this? @clodal

**Comment by clodal** [comment]
@likun7981 Yup thanks for your feedback. Your solution would be more comprehensive and the design for it has already been thought out. Of course, LinkComponent wouldn't be very useful after it is implemented as well. It's great! Looking forward to a `itemRender` patch. Would be a breaking change though.

**Comment by likun7981** [comment]
@clodal  The patch is publish, you can try

**Comment by clodal** [comment]
@likun7981 Cool, thanks i just tried it but it seems to break my code.

```
// components/Page.js
import Breadcrumbs from 'components/Breadcrumbs';
import { withRouter } from 'react-router-dom'; // v4

const Page = withRouter(
  ({ location }) => {
    console.log('location', location.pathname); // output: '/foo/bar'
    return (
      <div>
        {location && <Breadcrumbs pathname={location.pathname} />}
      </div>
    )
  }
);
```

```
// components/Breadcrumbs.js
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';
import BreadcrumbConfig from 'auto-breadcrumb';
import Breadcrumb from 'antd/lib/breadcrumb';

const Breadcrumbs = BreadcrumbConfig({
  Breadcrumb,
  BreadcrumbItem: Breadcrumb.Item,
  containerProps: { style: { textTransform: 'capitalize' } },
  itemRender: (name, path) => {
    console.log('name', name); // output: Home
    console.log('path', path); // output: /
    if (path) {
      return (<Link to={path}>{name}</Link>);
    }
    return `${name}(itemRender Custom Text Node)`;
  },
});

Breadcrumbs.propTypes = {
  pathname: PropTypes.string.isRequired,
};

export default Breadcrumbs;
```

Is this a bug, or am i missing something? thanks =)

**Comment by likun7981** [comment]
I try it with your config ,  the code is running and render `Home/404NotFound` , it is not break and the result is right.

What's wrong with the console print?

**Comment by clodal** [comment]
@likun7981 Oh yeah exactly, it renders `Home / 404NotFound` for me too. Expected outcome is `Home / Foo / Bar` before this patch. How would we do this dynamically now? Thanks !

**Comment by likun7981** [comment]
think you might be mistaken about the `itemRender` configuration option. 
you can understand  it like this 
 it is tell the `auto-breadcrumb` how to render item , but it can not tell `auto-breadcrumb`  what to display.  so  you should still config `staticRoutesMap` and `dynamicRoutesMap`.

**Comment by likun7981** [comment]
Oh yeah ,  I think I should update the release change log, it is my fualt.  you can see #2 .  I think the breadcrumb should be in strict accordance with the configuration, so now if the `staticRoutesMap` and `dynamicRoutesMap`  is not config the path, the item will display `404NotFound` not the path name.

**Comment by likun7981** [comment]
you can see [release-changelog](https://github.com/likun7981/auto-breadcrumb/releases/tag/v1.2.0) now, I update it
