### ISSUE TITLE
NotFound on route that exists

### ISSUE THREAD

**Issue by alexvance89** [likun7981/auto-breadcrumb#5]
Hi, I'm getting 404NotFound when the route exists. My friend executes the same code on macOS and it works, but on windows it does not unless I specify a static route for each possible route. Any route with a parameter in it ex: 'localhost/foo/{id}', it also says not found. This is being tested in Chrome on both operating systems.

This happened on v1.1.1 and v.1.2.2.

```
import BreadcrumbConfig from 'auto-breadcrumb';
import {withRouter} from 'react-router-dom';
```

```
const BreadCrumbs = BreadcrumbConfig({
    staticRoutesMap: {
        '/': 'Dashboard',
        '/administration': 'Administration',
        '/administration/users': 'Users',
        '/administration/users/new': 'New',
        '/administration/roles': 'Roles',
        '/administration/roles/new': 'New',
        '/dev-login': 'Development Settings'
    },
    containerProps: {
        className: 'breadcrumbs'
    }
});
```

```
export const BreadCrumbComponent = ({location}) =>
    <div>
        <BreadCrumbs pathname={location.pathname}/>
    </div>;

export const BreadCrumb = withRouter(BreadCrumbComponent);
```

**Comment by likun7981** [comment]
Sorry , I was test it on MacOs. I will test it with Windows.

**Comment by likun7981** [comment]
You can see [config example](https://github.com/likun7981/auto-breadcrumb/blob/gh-pages/demo/RecursivePaths.js#L6-L26), and you can try this [demo](https://likun7981.github.io/auto-breadcrumb/#/1/0/2/1) with windows, I think you have the wrong configuration

**Comment by serdimoa** [comment]
@alexvance89 , you can use dynamicRoutesMap in  you config, like this one
```javascript
const BreadCrumbs = BreadcrumbConfig({  
    dynamicRoutesMap: {
       '/foo/:id': ({id}) => `foo id:${id}`,  
    },
});
```
